/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Agrandir', 'sans-serif'],
        wide: ['AgrandirWide', 'sans-serif'],
        serif: ['PlantinMTPro', 'serif'],
      },
      colors: {
        black: 'var(--colorBlack)',
        white: 'var(--colorWhite)',
        grey: 'var(--colorGrey)',
        'grey-light': 'var(--colorGreyLight)',
        'beige-light': 'var(--colorBeigeLight)',
        beige: 'var(--colorBeige)',
        blue: 'var(--colorBlue)',
        red: 'var(--colorRed)',
        yellow: 'var(--colorYellow)',
      },
      spacing: {
        side: 'var(--sideSpacing)',
        'side-wide': 'var(--sideSpacingWide)',
        section: 'var(--sectionSpacing)',
        gutter: 'var(--gutterSpacing)',
        header: 'var(--headerHeight)',
        ticker: 'var(--tickerHeight)',
      },
      borderRadius: {
        DEFAULT: 'var(--borderRadius)',
      },
      fontSize: {
        7: 'var(--fontSize7)',
        8: 'var(--fontSize8)',
        9: 'var(--fontSize9)',
        10: 'var(--fontSize10)',
        11: 'var(--fontSize11)',
        12: 'var(--fontSize12)',
        14: 'var(--fontSize14)',
        15: 'var(--fontSize15)',
        16: 'var(--fontSize16)',
        17: 'var(--fontSize17)',
        18: 'var(--fontSize18)',
        20: 'var(--fontSize20)',
        22: 'var(--fontSize22)',
        24: 'var(--fontSize24)',
        28: 'var(--fontSize28)',
        30: 'var(--fontSize30)',
        32: 'var(--fontSize32)',
        33: 'var(--fontSize33)',
        34: 'var(--fontSize34)',
        36: 'var(--fontSize36)',
        39: 'var(--fontSize39)',
        40: 'var(--fontSize40)',
        42: 'var(--fontSize42)',
        44: 'var(--fontSize44)',
        45: 'var(--fontSize45)',
        46: 'var(--fontSize46)',
        50: 'var(--fontSize50)',
        52: 'var(--fontSize52)',
        54: 'var(--fontSize54)',
        60: 'var(--fontSize60)',
        70: 'var(--fontSize70)',
        80: 'var(--fontSize80)',
        92: 'var(--fontSize92)',
        94: 'var(--fontSize94)',
        120: 'var(--fontSize120)',
        150: 'var(--fontSize150)',
      },
    },
  },
  plugins: [],
};
